---
title: "Extract AMRfinderplus results for a species of interest"
output: html_document
date: "2024-10-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = 'png', echo = TRUE, message = FALSE, warning = FALSE,
                      cache = FALSE, fig.align = 'center')
knitr::opts_knit$set(root.dir = getwd())

# Data wrangling
library(tidyverse)
library(dplyr)

```

# set path to file of AMRFinderPlus from AllTheBacteria, downlaoded from https://osf.io/zgexh (0.5GB)
``` {r}
ATB_amrfp <- "AMRFP_results.tsv.gz"
```

# species calls from All The Bacteria
``` {r}
species_calls <- read_tsv("AllTheBacteria/ATB_species_calls.tsv.gz")
```

# ecoli

```{r }
ecoli <- species_calls %>% filter(Species=="Escherichia coli") %>% pull(Sample)
```

``` {r}
f <- function(x, pos) subset(x, Name %in% ecoli)

ecoli_AFP <- read_tsv_chunked(ATB_amrfp, DataFrameCallback$new(f), chunk_size = 10000)

# select columns to make file shareable in github
ecoli_AFP %>% select(Name, `Gene symbol`, `Hierarchy node`, Class, Subclass, `% Coverage of reference sequence`, `% Identity to reference sequence`) %>% 
  write_tsv(file="AllTheBacteria/ATB_Ecoli_AFP.tsv.gz")

dim(ecoli_AFP)
length(unique(ecoli_AFP$Name))
```

# salmonella

```{r }
salmonella <- species_calls %>% filter(Species=="Salmonella enterica") %>% pull(Sample)
```

``` {r}
f <- function(x, pos) subset(x, Name %in% salmonella)

salmonella_AFP <- read_tsv_chunked(ATB_amrfp, DataFrameCallback$new(f), chunk_size = 10000)

# select columns to make file shareable in github
salmonella_AFP %>% select(Name, `Gene symbol`, `Hierarchy node`, Class, Subclass, `% Coverage of reference sequence`, `% Identity to reference sequence`) %>% 
  write_tsv(file="AllTheBacteria/ATB_Salmonella_AFP.tsv.gz")

dim(salmonella_AFP)
length(unique(salmonella_AFP$Name))
```

# pseudomonas

```{r }
pseudomonas <- species_calls %>% filter(Species=="Pseudomonas aeruginosa") %>% pull(Sample)

```

``` {r}
f <- function(x, pos) subset(x, Name %in% pseudomonas)

pseudomonas_AFP <- read_tsv_chunked(ATB_amrfp, DataFrameCallback$new(f), chunk_size = 10000)

write_tsv(pseudomonas_AFP, file="AllTheBacteria/ATB_Pseudomonas_aeruginosa_AFP.tsv.gz")

dim(pseudomonas_AFP)
length(unique(pseudomonas_AFP$Name))
```

# enterobacter

```{r }
# get data for whole genus
enterobacter_genus <- species_calls %>% filter(grepl("Enterobacter",Species)) 
```

``` {r}
f <- function(x, pos) subset(x, Name %in% enterobacter_genus$Sample)

enterobacter_AFP <- read_tsv_chunked(ATB_amrfp, DataFrameCallback$new(f), chunk_size = 10000)

```

``` {r}
# write out with species annotated
enterobacter_AFP %>% full_join(enterobacter_genus, by=join_by("Name"=="Sample")) %>% write_tsv(file="ATB_Enterobacter_AFP.tsv.gz")

dim(enterobacter_AFP)
length(unique(enterobacter_AFP$Name))
enterobacter_genus %>% group_by(Species) %>% count() %>% arrange(-n)
```
