---
title: "PublicGenoPheno AllTheBacteria Enterobacter"
output: html_document
date: "2024-10-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = 'png', echo = TRUE, message = FALSE, warning = FALSE,
                      cache = FALSE, fig.align = 'center')
knitr::opts_knit$set(root.dir = getwd())

# Data wrangling
library(tidyverse)
library(dplyr)
library(patchwork)

source("../functions.R")
```


# read ATB AMRfinderplus calls - filter to high quality
```{r }

afp <-read_tsv("../AllTheBacteria/ATB_Enterobacter_AFP.tsv.gz") %>% filter(HQ)
denominator <- afp %>% select(Name) %>% unique() %>% nrow()

dim(afp)

denominator
```

# check for core genes
``` {r}

# gene frequency per species
species_count <- afp %>% group_by(Name, Species) %>% count() %>% distinct() %>% ungroup() %>% group_by(Species) %>% summarise(nspp=n()) %>% arrange(-nspp)

gene_counts <- afp %>% group_by(Name, `Gene symbol`, Class, Subclass, Species, `Element type`) %>% count() %>% distinct() %>% ungroup() %>% group_by(`Gene symbol`, Class, Subclass, Species, `Element type`) %>% count() %>% left_join(species_count, by="Species") %>% mutate(freq=n/nspp)

write_tsv(gene_counts, file="Enterobacter_gene_freq_per_species.tsv")

# AMR markers with per-species frequency >90% (candidate core genes)
gene_counts %>% filter(nspp>10 & freq>0.9 & `Element type`=="AMR") %>% view()

# plot AMR markers with per-species frequency >90% (candidate core genes)
gene_counts %>% filter(nspp>10 & freq>0.9 & `Element type`=="AMR") %>%
  mutate(label=paste0(Species, " (n=", nspp, ")")) %>%
  arrange(-nspp) %>%
  ggplot(aes(y=label, x=freq, fill=`Gene symbol`)) + geom_col(position='dodge') + facet_wrap(~`Gene symbol`)

ggsave(width=10, height=10, file="Enterobacter_candidate_coreGenes.pdf")
```


# read AST data - from NCBI
```{r }

ast<-read_delim("../AST/AST_Enterobacter.tsv.gz") %>% rename(BioSample=`#BioSample`)

length(unique(ast$BioSample))

ast %>% group_by(BioSample) %>% summarise(n=length(unique((Antibiotic))))%>% pull(n) %>% summary()

```


# get AMRfinderplus and AST data where both are available
``` {r}
sum(unique(ast$BioSample) %in% afp$Name[afp$HQ])

# AST data for strains with AMRfinder results
ast_matched <- ast %>% filter(BioSample %in% afp$Name[afp$HQ])

# AMRfinder results, for strains with matching AST data from NCBI
afp_matched <- afp %>% filter(Name %in% ast$BioSample & HQ)

# check objects
dim(ast_matched)
ast_matched %>% pull(BioSample) %>% unique() %>% length()

dim(afp_matched)
afp_matched %>% pull(Name) %>% unique() %>% length()

# species
afp_matched %>% select(Name, Species) %>% distinct() %>% group_by(Species) %>% count()
```

# Enterobacter hormaechei_A
``` {r}
afp_eh <- afp_matched %>% filter(Species=="Enterobacter hormaechei_A")
ast_eh <- ast_matched %>% filter(BioSample %in% afp_eh$Name)
```

# solo markers for ciprofloxacin
``` {r}
cip_quinolone <- solo_marker_atb(ast_matched = ast_eh, afp_matched=afp_eh %>% filter(`Gene symbol`!="oqxB"), antibiotic = "ciprofloxacin", refgene_class = "QUINOLONE")

cip_quinolone$solo_stats

# excluding oqxAB as this is core
cip_quinolone_noOqx <- solo_marker_atb(ast_matched = ast_eh, afp_matched=afp_eh %>% filter(!(`Gene symbol` %in% c("oqxB", "oqxA"))), antibiotic = "ciprofloxacin", refgene_class ="QUINOLONE")

cip_quinolone_noOqx$solo_stats
cip_quinolone_noOqx$combined_plot

```

``` {r}
cip_binary <- getBinMatrix(ast_matched = ast_eh, afp_matched = afp_eh %>% filter(!(`Gene symbol` %in% c("oqxB", "oqxA"))), antibiotic = "ciprofloxacin", refgene_class = "QUINOLONE", maf=5)

cip_model <- logistf(resistant ~ ., data=cip_binary)

cip_logreg <- logreg_details(cip_model) %>% 
  mutate(sig=if_else(pval<0.05, TRUE, FALSE)) %>%
  filter(marker != "(Intercept)") %>%
  mutate(marker=gsub("`","",marker)) %>%
  ggplot(aes(y=marker, col=sig)) + 
  geom_vline(xintercept=0) + 
  geom_linerange(aes(xmin=ci.lower, xmax=ci.upper)) + 
  geom_point(aes(x=est)) + 
  scale_color_manual(values=c("grey", "black")) + 
  theme_light() + labs(x="Logist regression coefficient (95% CI)", col="p<0.05")

cip_logreg

```

# no AST data on fos
``` {r}
ast_eh %>% filter(Antibiotic=="fosfomycin") %>% nrow()
```

